### ISSUE TITLE
ProcessTweets

### ISSUE THREAD

**Issue by Jane03** [toshiakit/AnalyzeTwitter#2]
Hi,

Can you give me an explanation on these codes:

 % iterate over tweets
            tokenized = cell(size(tweets.Tweet));
            word_list = {};
            
            for i = 1:length(tweets.Tweet)
                % lower case 
                tweet = lower(tweets.Tweet{i});
                % remove numbers

i have error on the " tokenized = cell(size(tweets.Tweet));" and i don't understand why?
these codes are found on the ProcessTweets.m

Thanks for your help

**Comment by toshiakit** [comment]
tokenized is an empty cell array initialized to hold values processed from the for-loop. Because the for-loop iterate over the length of the tweets.Tweet, This cell array has to have the same size as the tweet.Tweet, so I use size to get it.  The error message you get should give you a clue why it is not working. Probably because tweets.Tweet is not available in your workspace?

**Comment by Jane03** [comment]
Thanks for your explanation.
